### ISSUE TITLE
Compress to target size

### ISSUE THREAD

**Issue by tmorrow-hyphensolutions** [fastmonkeys/angular-ahdin#3]
I could use your compress function within a loop with a decreasing percent value, and keep checking the resulting blob length to see if the percent achieved the target blob size.

Is there a more straight forward way to do that?

We have a database size limitation for images uploaded to our site.

Thanks!

**Comment by ropsu** [comment]
@tmorrow-hyphensolutions, Unfortunately, you can tell the size of the compressed image only after compression. What we've done in our projects is that we've defined a certain `maxWidth` that makes sure all the images are small enough after compression. After all, decreasing image height or width decreases the image size effectively while decreasing percent value makes images rather fuzzy rather fast.

**Comment by tmorrow-hyphensolutions** [comment]
Thanks, good point. I’ll play with it. Your library is the only one that does this I think ☺

**Comment by ropsu** [comment]
Cool, let me know if there's anything I can help you with.
